---

language: 'python'
python: '2.7'

virtualenv:
  system_site_packages: True

before_install: True
install: True

script:
  - sudo useradd -m vagrant
  - git clone --depth 1 https://github.com/nickjj/rolespec
  - cd rolespec ; bin/rolespec -r https://github.com/pablocrivella/ansible-roles-specs.git
