---
- hosts: all

  roles:
  - role: pablocrivella.rbenv
    rbenv_env: user
    rbenv_version: v0.4.0
    rbenv_global: 2.2.2
    rbenv_rubies:
      - 2.2.2
    rbenv_default_gems:
      - bundler
      - pry
    rbenv_users:
      - name: root
        home: /root
